server:
  port: 80
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/geppa
    username: geppaadmin
    password: geppa123
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

cors:
  originPatterns: "http://localhost:80,http://localhost:3000,https://restapi.com,http://localhost:5173"