server:
  port: 80
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    #    url: jdbc:postgresql://db:5432/geppa
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:geppa}
    username: ${DB_USER:geppaadmin}
    password: ${DB_PASSWORD:geppa123}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: email@exemple.com
    password: ###########
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

cors:
  originPatterns: "${CORS_HOSTS:http://localhost:80},http://localhost:3000,https://restapi.com,http://localhost:5173"
