version: '3.9'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: geppa
    expose:
      - 5432
    volumes:
        - db-data:/var/lib/postgresql/data

  boletins-informativos-api:
    image: geppa/boletins
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports:
      - "80:80"

volumes:
    db-data: